# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
#Comment out if you don't want disqus 
url: http://suchac.dev
baseurl: /
title: Suchac.dev
author: Suchac
description: Personal resume and blog
avatar: author.jpg
email: suchac.dev@gmail.com
github: suchac
twitter: Suchac15

# needed for travis-ci build
exclude: [vendor]
