# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
#Comment out if you don't want disqus 
url: http://suchac.dev
baseurl: /
title: Suchac.dev
author: Suchac
description: Personal resume and blog
avatar: author.jpg
email: suchac.dev@gmail.com
github: suchac
facebook: psuchy15
instagram: suchaac
twitter: Suchac15
linkedin: petrsuchy
#stackoverflow: users/2114610/suchac   #e.g: users/2735833/proton1h1
#disqus: username
google_analytics: UA-92996473-1


# needed for travis-ci build
exclude: [vendor]
