# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
#Comment out if you don't want disqus 
url: https://suchac.dev
baseurl: /
title: Suchac.dev
author: Suchac
description: Software Developer, world traveller, photographer. Personal site and blog about programming, tech, and travel.
avatar: author.jpg
keywords: software developer, programming, web development, travel, photography
email: suchac.dev@gmail.com
github: suchac
twitter: suchac_dev

# needed for travis-ci build
exclude: [vendor]
